dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.5.0
  dio: ^5.4.0
  intl: ^0.19.0

  speech_to_text: ^6.6.0
  flutter_tts: ^3.8.5

  firebase_core: ^2.27.0
  firebase_auth: ^4.17.0

  razorpay_flutter: ^1.3.7
